### ISSUE TITLE
Navbar section

### ISSUE THREAD

**Issue by Rahul-Rajeevan** [Rahul-Rajeevan/b35_collab#7]
Create a responsive Navbar as shown
<img width="950" alt="image" src="https://github.com/Rahul-Rajeevan/b35_collab/assets/101565872/719f4ee4-34e0-4612-9fd4-11dff0814608">

- [x] Navbar created
- [x] Responsiveness is added
- [x] Links are working
- [x] Call to actions are working as expected

**Comment by ar98nab** [comment]
waiting for links for other pages @Rahul-Rajeevan

**Comment by Rahul-Rajeevan** [comment]
Got the updated links, please work on adding it ASAP @ar98nab

**Comment by ar98nab** [comment]
my task is finished

**Comment by ar98nab** [comment]
m
